"""
DeepShield — PDF Report Router (JSON store)
GET /report/{detection_id}?token=<bearer_token>
Supports token via query param so browser window.open() works.
"""

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse
from typing import Optional
import io

from backend.database import _load

router = APIRouter(prefix="/report", tags=["Reports"])


def _resolve_user(token: Optional[str]) -> dict:
    """Extract user from token (same logic as Bearer auth)."""
    if not token:
        raise HTTPException(status_code=401, detail="Token required.")
    user_id = token.split(".")[-1]
    if not user_id:
        raise HTTPException(status_code=401, detail="Invalid token.")
    data = _load()
    user = data["users"].get(user_id)
    if not user:
        raise HTTPException(status_code=401, detail="User not found.")
    return {**user, "_id": user_id, "id": user_id}


@router.get("/{detection_id}")
async def download_report(
    detection_id: str,
    token: Optional[str] = Query(None),
):
    user = _resolve_user(token)
    data = _load()
    doc = data["detections"].get(detection_id)
    if not doc or doc.get("user_id") != user["_id"]:
        raise HTTPException(status_code=404, detail="Detection not found.")

    doc = {"id": detection_id, **doc}

    try:
        from utils.report_generator import generate_pdf_report
        pdf_bytes = generate_pdf_report(doc, user)
    except ImportError:
        # reportlab not installed — return a plain text report
        pdf_bytes = _generate_text_report(doc, user)
        filename = f"deepshield_report_{detection_id[:8]}.txt"
        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="text/plain",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    filename = f"deepshield_report_{detection_id[:8]}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


def _generate_text_report(doc: dict, user: dict) -> bytes:
    """Plain text fallback when reportlab is not installed."""
    result = doc.get("result", {})
    lines = [
        "=" * 60,
        "DEEPSHIELD — SYNTHETIC MEDIA DETECTION REPORT",
        "=" * 60,
        f"Detection ID : {doc.get('id', 'N/A')}",
        f"Analyst      : {user.get('name', 'N/A')}",
        f"Date         : {doc.get('created_at', 'N/A')}",
        f"Filename     : {doc.get('filename', 'N/A')}",
        f"Media Type   : {doc.get('media_type', 'N/A').upper()}",
        "-" * 60,
        f"VERDICT      : {doc.get('prediction', 'N/A')}",
        f"Confidence   : {doc.get('confidence', 0):.1f}%",
        f"Risk Level   : {doc.get('risk_level', 'N/A')}",
        f"Fake Prob    : {result.get('fake_probability', 0)*100:.2f}%",
        f"Real Prob    : {result.get('real_probability', 0)*100:.2f}%",
        f"Model Used   : {result.get('model_used', 'N/A')}",
        f"Process Time : {result.get('processing_time', 0):.3f}s",
        "-" * 60,
        "AI EXPLANATION:",
        result.get("ai_explanation", "No explanation available."),
        "=" * 60,
        "Generated by DeepShield v1.0.0 | B.Tech CSE Final Year Project",
    ]
    return "\n".join(lines).encode("utf-8")
